export const channels = [
  {
    id_channel: "discovery",
    logo: "https://disctest.imgix.net/files/logos/Discovery-Logo-white%20%282%29.png",
    logo_svg: "https://disctest.imgix.net/files/logos/discovery_8.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/discovery_7.svg",
    noflip: false,
    shortname: "discovery",
    title: "Discovery",
    url: "https://www.tudiscovery.com/discovery",
    url_programming: "/discovery/tv/programacion"
  },
  {
    id_channel: "animalPlanet",
    logo: "https://disctest.imgix.net/files/logos/ANIMAL-PLANET-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/animal%20planet_17.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/animal%20planet_16.svg",
    noflip: false,
    shortname: "animal-planet",
    title: "Animal Planet",
    url: "https://www.tudiscovery.com/animal-planet",
    url_programming: "/animal-planet/tv/programacion"
  },
  {
    id_channel: "id",
    logo: "https://disctest.imgix.net/files/2018-12/ID-Logo-white.png",
    logo_svg: "https://disctest.imgix.net/files/logos/id.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/id_2.svg",
    noflip: false,
    shortname: "id",
    title: "Investigation Discovery",
    url: "https://www.tudiscovery.com/id",
    url_programming: "/id/tv/programacion",
  },
  {
    id_channel: "turbo",
    logo: "https://disctest.imgix.net/files/2018-12/TURBO-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/turbo_2.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/turbo_1_0.svg",
    noflip: false,
    shortname: "turbo",
    title: "Turbo",
    url: "https://www.tudiscovery.com/turbo",
    url_programming: "/turbo/tv/programacion"
  },
  {
    id_channel: "discoveryhh",
    logo: "https://disctest.imgix.net/files/2018-12/HH-Logo-white.png",
    logo_svg: "https://disctest.imgix.net/files/logos/hh.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/h%26h.svg",
    noflip: false,
    shortname: "discoveryhh",
    title: "Discovery Home&Health",
    url: "https://www.tudiscovery.com/discoveryhh",
    url_programming: "/discoveryhh/tv/programacion"
  },
  {
    id_channel: "tlc",
    logo: "https://disctest.imgix.net/files/2018-12/TLC-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/tlc.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/tlc_2.svg",
    noflip: false,
    shortname: "tlc",
    title: "TLC",
    url: "https://www.tudiscovery.com/tlc",
    url_programming: "/tlc/tv/programacion",
  },
  {
    id_channel: "hgtv",
    logo: "https://disctest.imgix.net/files/logos/hgtv.svg__0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/hgtv.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/hgtv_0.svg",
    noflip: true,
    shortname: "hgtv",
    title: "HGTV",
    url: "https://www.tudiscovery.com/hgtv/tv/programacion",
    url_programming: "/hgtv/tv/programacion",
  },
  {
    id_channel: "kids",
    logo: "https://disctest.imgix.net/files/2018-12/DKIDS-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/dk.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/kids_3.svg",
    noflip: true,
    shortname: "kids",
    title: "Discovery Kids",
    url: "https://www.discoverykidsplay.com/",
    url_programming: "https://www.discoverykidsplay.com/",
  },
  {
    id_channel: "food",
    logo: "https://disctest.imgix.net/files/2018-12/FoodNetwork_LOGO_Blanco_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/food%20network_3.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/food%20network_5.svg",
    noflip: false,
    shortname: "food",
    title: "Food Network",
    url: "https://foodnetworklatam.com/",
    url_programming: "https://foodnetworklatam.com/",
  },
];

export const channelsBrazil = [
  {
    id_channel: "discovery",
    logo: "https://disctest.imgix.net/files/logos/Discovery-Logo-white%20%282%29.png",
    logo_svg: "https://disctest.imgix.net/files/logos/discovery_8.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/discovery_7.svg",
    noflip: false,
    shortname: "discovery",
    title: "Discovery",
    url: "https://www.discoverybrasil.com/discovery",
    url_programming: "/discovery/tv/programacao"
  },
  {
    id_channel: "animalPlanet",
    logo: "https://disctest.imgix.net/files/logos/ANIMAL-PLANET-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/animal%20planet_17.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/animal%20planet_16.svg",
    noflip: false,
    shortname: "animal-planet",
    title: "Animal Planet",
    url: "https://www.discoverybrasil.com/animal-planet",
    url_programming: "/animal-planet/tv/programacao"
  },
  {
    id_channel: "id",
    logo: "https://disctest.imgix.net/files/2018-12/ID-Logo-white.png",
    logo_svg: "https://disctest.imgix.net/files/logos/id.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/id_2.svg",
    noflip: false,
    shortname: "id",
    title: "Investigation Discovery",
    url: "https://www.discoverybrasil.com/id",
    url_programming: "/id/tv/programacao",
  },
  {
    id_channel: "turbo",
    logo: "https://disctest.imgix.net/files/2018-12/TURBO-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/turbo_2.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/turbo_1_0.svg",
    noflip: false,
    shortname: "turbo",
    title: "Turbo",
    url: "https://www.discoverybrasil.com/turbo",
    url_programming: "/turbo/tv/programacao"
  },
  {
    id_channel: "discoveryhh",
    logo: "https://discovery-latam-prod.imgix.net/files/logos/HH-Logo-white.png",
    logo_svg: "https://discovery-latam-prod.imgix.net/files/logos/hh_4.svg",
    logo_svg_circle: "https://discovery-latam-prod.imgix.net/files/logos/h%26h_0.svg",
    noflip: false,
    shortname: "discoveryhh",
    title: "Discovery Home&Health",
    url: "/discoveryhh",
    url_programming: "/discoveryhh/tv/programacao",
  },
  {
    id_channel: "tlc",
    logo: "https://disctest.imgix.net/files/2018-12/TLC-Logo-white_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/tlc.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/tlc_2.svg",
    noflip: false,
    shortname: "tlc",
    title: "TLC",
    url: "https://www.discoverybrasil.com/tlc",
    url_programming: "/tlc/tv/programacao",
  },
  {
    id_channel: "discoveryScience",
    logo: "https://discovery-latam-prod.imgix.net/files/logos/science_white_0.png",
    logo_svg: "https://discovery-latam-prod.imgix.net/files/logos/science_3.svg",
    logo_svg_circle: "https://discovery-latam-prod.imgix.net/files/logos/science_4.svg",
    noflip: true,
    shortname: null,
    title: "Discovery Science",
    url: "https://www.discoverybrasil.com/science/tv/programacao",
    url_programming: "https://www.discoverybrasil.com/science/tv/programacao",
  },
  {
    id_channel: "hgtv",
    logo: "https://disctest.imgix.net/files/logos/hgtv.svg__0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/hgtv.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/hgtv_0.svg",
    noflip: true,
    shortname: "hgtv",
    title: "HGTV",
    url: "https://www.discoverybrasil.com/hgtv/tv/programacao",
    url_programming: "/hgtv/tv/programacao",
  },
  {
    id_channel: "kids",
    logo: "https://discovery-latam-prod.imgix.net/files/2018-12/DKIDS-Logo-white_0.png",
    logo_svg: "https://discovery-latam-prod.imgix.net/files/logos/dkids_play_white.svg",
    logo_svg_circle: "https://discovery-latam-prod.imgix.net/files/logos/kids_5.svg",
    noflip: true,
    shortname: "kids",
    title: "Discovery Kids",
    url: "https://www.discoverykidsplay.com.br/",
    url_programming: "https://www.discoverykidsplay.com.br/",
  },
  {
    id_channel: "discoveryCivilization",
    logo: "https://discovery-latam-prod.imgix.net/files/logos/civilization_white_0.png",
    logo_svg: "https://discovery-latam-prod.imgix.net/files/logos/dciv.svg",
    logo_svg_circle: "https://discovery-latam-prod.imgix.net/files/logos/civilization.svg",
    noflip: true,
    shortname: "kids",
    title: "Discovery Civilization",
    url: "https://www.discoverybrasil.com/civilization/tv/programacao",
    url_programming: "https://www.discoverybrasil.com/civilization/tv/programacao",
  },
  {
    id_channel: "discoveryTheater",
    logo: "https://discovery-latam-prod.imgix.net/files/logos/theater_white_0.png",
    logo_svg: "https://discovery-latam-prod.imgix.net/files/logos/theater_0_0.svg",
    logo_svg_circle: "https://discovery-latam-prod.imgix.net/files/logos/theater_2.svg",
    noflip: true,
    shortname: "kids",
    title: "Discovery Theater",
    url: "https://www.discoverybrasil.com/theater/tv/programacao",
    url_programming: "https://www.discoverybrasil.com/theater/tv/programacao",
  },
  {
    id_channel: "food",
    logo: "https://disctest.imgix.net/files/2018-12/FoodNetwork_LOGO_Blanco_0.png",
    logo_svg: "https://disctest.imgix.net/files/logos/food%20network_3.svg",
    logo_svg_circle: "https://disctest.imgix.net/files/logos/food%20network_5.svg",
    noflip: false,
    shortname: "food",
    title: "Food Network",
    url: "https://foodnetworklatam.com/",
    url_programming: "https://foodnetworklatam.com/",
  },
  {
    id_channel: "discoveryWorld",
    logo: "https://discovery-latam-prod.imgix.net/files/logos/world_2.png",
    logo_svg: "https://discovery-latam-prod.imgix.net/files/logos/world_2.svg",
    logo_svg_circle: "https://discovery-latam-prod.imgix.net/files/logos/world_4.svg",
    noflip: true,
    shortname: "food",
    title: "Discovery World",
    url: "https://www.discoverybrasil.com/world/tv/programacao",
    url_programming: "https://www.discoverybrasil.com/world/tv/programacao",
  }
];
